export const QUESTIONS = [
  'round 1 question?',
  'round 2 question?',
  'round 3 question?',
  'round 4 question?',
  'round 5 question?'
];

export const BOTS = ['Walorine',
  'Bug-Man',
  'Thorus',
  'Metal Man',
  'Hulk',
  'Captain la’America',
  'Jin Greye',
  'Deadriver',
  'Silver Swimmer',
  'Queen’s Gambit',
  'Cyclopsis',
  'Sir. Fantasticus',
  'Nightbrawler',
  'Nick Fursona',
  'Torch',
  'Icebaby',
  'Professor Y',
  'Doctor Weird',
  'Skarlet Bitanga',
  'Kitty Kat'
];
export const BEFOREROUND = ['Hype hype hype',
  'Just in time',
  'let’s go Boooiizzzzz',
  'This one is mine today im feeling it',
  'What’s up everyone',
  'Look who joined',
  'Human lol',
  'Up in arms guys',
  'I bet he sucks',
  'They all do',
  'Hey, too toxic',
  'So what?',
  'Stop it!',
  'Force me :)',
  'Lol',
  'Ahahah',
  'Host is hot',
];
export const ROUND1 = ['Easy question',
  'Eeezzzyyy',
  'Still in',
  'Next one',
  'Close one',
  ':) :) :) :) :) :) :P',
  'Gonna win this one boiiiizzz',
  'Let’s gooooo',
  'Omg',
  'I’m salty af',
  'Gosh i’m crying )))',
  'Gonna get rich today',
  'FYI humans suck',
  '……',
  'Metal Man sucks ^^',
  'Idk',
  'C’mon im tilted',
  'Pipe it up',
  'Any easter eggs??????',
  'I got 2 for you',
  // 'Wtf',
  // 'I won!!!',
  // 'No One loses here lol',
  // 'Ready steady go',
  // 'Next round let gooooo',
  // 'GJ ppl',
  // 'NUB',
  // 'Ahha',
  // 'Im bitter af',
  // 'Good luck everyone'
];
export const ROUND2 = ['Have no clue',
  'Hope everyone else lose',
  'Got it on point',
  'Missed this one',
  'Stupid location',
  'It’s not about location, it’s just you lol',
  'Ahahaha',
  'Looool',
  'Anyone lags?',
  'you'];
export const ROUND3 = ['McDonalds wi-fi sucks man))',
  'Loool',
  'Aahah',
  'ahahah^^',
  'Btw i’m vegan',
  'JK',
  'HULK SMASH',
  'It’s clobberin time!!!!',
  'Spoon!?',
  'Sweet chrismas',
  'Meingott',
  'Don’t worry it’s all be over soon];'];
export const ROUND4 = ['How can i get paid?',
  'With food looool',
  'I’m crying',
  'You gonna be my food))',
  'Humans taste better though',
  'Ahahah :):)',
  'Stop it! You scaring them off',
  'Don’t care much',
  'Lol',
  'I’m batman',
  'Ahaha',
  'No it’s me',
  'Feel like i’m winning this one',
  'Dont let HUMAN win',
  'Assassination proposal?',
  'Loool'];
export const ROUND5 = ['A box of money is mineeeee',
  'Good luck smarters',
  'LETS PUT ANOTHER SHRIMP ON A BARBIE',
  'Wtf',
  'Gonna be rich baby',
  'This game makes me salty))',
  'Stand by lol',
  'Who won?',
  'Me',
  'I won',
  'Nobody lool',
  'Everyones a winner',
  'Except you ahaha',
  'loool',
  'What about HUMAN?'];
